// File automatically generated by fshasher

#pragma once

#include <utility>
#include <array>
#include <cstdint>

extern const std::array<uint8_t, 32> ApotosShamarHashes[];
extern const std::pair<const char *, uint32_t> ApotosShamarFiles[];
extern const size_t ApotosShamarFilesSize;

