// File automatically generated by fshasher

#pragma once

#include <utility>
#include <array>
#include <cstdint>

extern const std::array<uint8_t, 32> EmpireCityAdabatHashes[];
extern const std::pair<const char *, uint32_t> EmpireCityAdabatFiles[];
extern const size_t EmpireCityAdabatFilesSize;

